### PR TITLE
add missing idPrefix as default value to config

### LINKED ISSUE #36: Missing 'idPrefix' in config.js
The 'idPrefix' default option is missing in config.js. And you will get `id="undefined<ID>"` in result.
Just add one string to easily fix it.
  ```
  ...
  classPrefix: false,
  idPrefix: false
};
```

### PR DESCRIPTION
**Pull request by noxan**
Close #36

### CODE REVIEW

**Comment by sairion** [comment]
Thank you!

**Comment by noxan** [comment]
Just happy to remove the hot fix from my project, once this is released, thanks for the quick merge.

And also thanks to @Climenty for reporting, helped me to verify my local fix.

**Comment by sairion** [comment]
@noxan Just released svg-inline-loader@0.7.1 to NPM

**Comment by noxan** [comment]
That's fast mate, thanks a lot! :)

**Pull request merged**
